version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_cohorts:
    run: cohortextractor:latest generate_cohort
    outputs:
      highly_sensitive:
        covid_cohort: output/input_covid.csv
        pneumonia_cohort: output/input_pneumonia.csv
        ctrl_2019_cohort: output/input_control_2019.csv
        ctrl_2020_cohort: output/input_control_2020.csv

  000_covid:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "covid"
    needs: [generate_cohorts]
    outputs:
      moderately_sensitive:
        graph: output/length_of_stay_covid.svg
      highly_sensitive:
        analysis_dataset: output/cohort_rates_covid.dta

  000_pneumonia:
    run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "pneumonia"
    needs: [generate_cohorts]
    outputs:
      moderately_sensitive:
        graph: output/length_of_stay_pneumonia.svg
      highly_sensitive:
        analysis_dataset: output/cohort_rates_pneumonia.dta

  201_covid:
    run: stata-mp:latest analysis/201_cr_simple_rates.do "covid"
    needs: [000_covid]
    outputs:
      moderately_sensitive:
        graph: output/tabfig/rates_summary_covid.csv

  201_pneumonia:
    run: stata-mp:latest analysis/201_cr_simple_rates.do "pneumonia"
    needs: [000_pneumonia]
    outputs:
      moderately_sensitive:
        graph: output/tabfig/rates_summary_pneumonia.csv

  matching_control_2019_dvt:
    run: python:latest python analysis/match_running.py "control_2019" "dvt"
    needs: [generate_cohorts]
    outputs:
      moderately_sensitive:
        matching_report: output/matching_report_control_2019_dvt.txt
      highly_sensitive:
        combined: output/matched_combined_control_2019_dvt.csv

  matching_control_2019_pe:
    run: python:latest python analysis/match_running.py "control_2019" "pe"
    needs: [generate_cohorts]
    outputs:
      moderately_sensitive:
        matching_report: output/matching_report_control_2019_pe.txt
      highly_sensitive:
        combined: output/matched_combined_control_2019_pe.csv

  matching_control_2019_stroke:
    run: python:latest python analysis/match_running.py "control_2019" "stroke"
    needs: [generate_cohorts]
    outputs:
      moderately_sensitive:
        matching_report: output/matching_report_control_2019_stroke.txt
      highly_sensitive:
        combined: output/matched_combined_control_2019_stroke.csv

  matching_control_2020_dvt:
    run: python:latest python analysis/match_running.py "control_2020" "dvt"
    needs: [generate_cohorts]
    outputs:
      moderately_sensitive:
        matching_report: output/matching_report_control_2020_dvt.txt
      highly_sensitive:
        combined: output/matched_combined_control_2020_dvt.csv

  matching_control_2020_pe:
    run: python:latest python analysis/match_running.py "control_2020" "pe"
    needs: [generate_cohorts]
    outputs:
      moderately_sensitive:
        matching_report: output/matching_report_control_2020_pe.txt
      highly_sensitive:
        combined: output/matched_combined_control_2020_pe.csv

  matching_control_2020_stroke:
    run: python:latest python analysis/match_running.py "control_2020" "stroke"
    needs: [generate_cohorts]
    outputs:
      moderately_sensitive:
        matching_report: output/matching_report_control_2020_stroke.txt
      highly_sensitive:
        combined: output/matched_combined_control_2020_stroke.csv
