version: "3.0"

expectations:
  population_size: 20000

actions:
  generate_covid_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid
    outputs:
      highly_sensitive:
        cohort: output/input_covid.csv

  generate_covid_community_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_community
    outputs:
      highly_sensitive:
        cohort: output/input_covid_community.csv

  generate_pneumonia_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_pneumonia
    outputs:
      highly_sensitive:
        cohort: output/input_pneumonia.csv

  generate_measure_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2019-02-01 to 2020-10-01 by month"
    outputs:
      highly_sensitive:
        measure_data: output/input_measures*.csv

  calculate_measures:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_measures
    needs: [generate_measure_cohort]
    outputs:
      moderately_sensitive:
        measure: output/measure_*_rate.csv

  draw_timeseries:
    run: python:latest python analysis/time_series_plots.py
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        graph: output/event_count_time_series.svg

  covid_rates_cohort:
   run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "covid"
   needs: [generate_covid_cohort]
   outputs:
     moderately_sensitive: 
	outcome_dist: output/tabfig/outcome_distribution_covid.csv
     highly_sensitive:
        analysis_dataset: output/cohort_rates_covid.dta

  covid_community_rates_cohort:
   run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "covid_community"
   needs: [generate_covid_community_cohort]
   outputs:
     moderately_sensitive: 
	outcome_dist: output/tabfig/outcome_distribution_covid_community.csv
     highly_sensitive:
        analysis_dataset: output/cohort_rates_covid_community.dta

  pneumonia_rates_cohort:
   run: stata-mp:latest analysis/000_cr_define_covariates_simple_rates.do "pneumonia"
   needs: [generate_pneumonia_cohort]
   outputs:
     moderately_sensitive: 
	outcome_dist: output/tabfig/outcome_distribution_pneumonia.csv
     highly_sensitive:
        analysis_dataset: output/cohort_rates_pneumonia.dta

  covid_rates:
    run: stata-mp:latest analysis/201_cr_simple_rates.do "covid"
    needs: [covid_rates_cohort]
    outputs:
      moderately_sensitive:
        rates: output/tabfig/rates_summary_covid.csv

  covid_comm_rates:
    run: stata-mp:latest analysis/201_cr_simple_rates.do "covid_community"
    needs: [covid_community_rates_cohort]
    outputs:
      moderately_sensitive:
        rates: output/tabfig/rates_summary_covid_community.csv

  pneumonia_rates:
    run: stata-mp:latest analysis/201_cr_simple_rates.do "pneumonia"
    needs: [pneumonia_rates_cohort]
    outputs:
      moderately_sensitive:
        rates: output/tabfig/rates_summary_pneumonia.csv

  baseline_characteristics:
    run: stata-mp:latest analysis/400_baseline_characteristics.do
    needs: [covid_rates_cohort, covid_community_rates_cohort, pneumonia_rates_cohort]
    outputs:
      moderately_sensitive:
        tables: output/tabfig/an_descriptiveTable_*.txt
